version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - common
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    restart: unless-stopped
    build: ./app
    # to ensure app starts to connect to db after db starts
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node dist/main'
    networks:
      - common
    ports:
      - 3000:3000

networks:
  common:
